"""
report.py — Report Generation (Prototype).

Builds a simple, professional one-page PDF report for a single resume
analysis, using reportlab. Saved into reports/generated/ so it can be
served back to the user as a download.
"""

import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REPORTS_DIR = os.path.join(PROJECT_ROOT, "reports", "generated")

PURPLE = HexColor("#6e44e8")
DARK = HexColor("#201a38")
MUTED = HexColor("#746d88")
GREEN = HexColor("#22c58b")
RED = HexColor("#e5685f")


def _score_color(score: float):
    if score >= 80:
        return GREEN
    if score >= 50:
        return HexColor("#d99a2b")
    return RED


def generate_report_pdf(entry: dict) -> str:
    """
    Build a PDF report for one analysis entry (a dict as returned by
    database.get_analysis_by_id) and return the file path it was saved to.
    """
    os.makedirs(REPORTS_DIR, exist_ok=True)
    filename = f"report_{entry['id']}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)

    doc = SimpleDocTemplate(
        filepath, pagesize=A4,
        topMargin=22 * mm, bottomMargin=20 * mm,
        leftMargin=22 * mm, rightMargin=22 * mm,
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=20,
        textColor=DARK, spaceAfter=2, alignment=TA_LEFT,
    )
    meta_style = ParagraphStyle(
        "Meta", parent=styles["Normal"], fontSize=9.5,
        textColor=MUTED, spaceAfter=14,
    )
    heading_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"], fontSize=12.5,
        textColor=DARK, spaceBefore=16, spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"], fontSize=10.5,
        textColor=DARK, leading=15,
    )
    score_style = ParagraphStyle(
        "Score", parent=styles["Normal"], fontSize=34,
        textColor=_score_color(entry["match_score"]), leading=38,
    )

    story = []

    story.append(Paragraph("ResumeLens — ATS Analysis Report", title_style))
    created_at = entry["created_at"][:16].replace("T", " ")
    story.append(Paragraph(
        f"Resume: {entry['resume_filename']} &nbsp;&nbsp;|&nbsp;&nbsp; Generated: {created_at}",
        meta_style,
    ))
    story.append(HRFlowable(width="100%", color=HexColor("#eeeaf8"), thickness=1))

    # Score section
    story.append(Paragraph("ATS Match Score", heading_style))
    story.append(Paragraph(f"{entry['match_score']}<font size=14>/100</font>", score_style))
    if entry.get("skill_match_score") is not None:
        story.append(Paragraph(
            f"Skill coverage: {entry['skill_match_score']}% of the job's required skills found in this resume.",
            body_style,
        ))
    story.append(Spacer(1, 6 * mm))

    # Matched / Missing skills side by side
    matched = ", ".join(entry["matched_skills"]) if entry["matched_skills"] else "None found"
    missing = ", ".join(entry["missing_skills"]) if entry["missing_skills"] else "None — good coverage"

    skills_table = Table(
        [
            [Paragraph("<b>Matching Skills</b>", body_style), Paragraph("<b>Missing Skills</b>", body_style)],
            [Paragraph(matched, body_style), Paragraph(missing, body_style)],
        ],
        colWidths=[75 * mm, 75 * mm],
    )
    skills_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BACKGROUND", (0, 0), (0, -1), HexColor("#f3f0ff")),
        ("BACKGROUND", (1, 0), (1, -1), HexColor("#fdf2f1")),
        ("BOX", (0, 0), (0, -1), 0.5, HexColor("#e4dffa")),
        ("BOX", (1, 0), (1, -1), 0.5, HexColor("#f6dbd8")),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(skills_table)

    # Suggestions
    story.append(Paragraph("Suggestions to Improve", heading_style))
    for suggestion in entry["suggestions"]:
        story.append(Paragraph(f"•&nbsp;&nbsp;{suggestion}", body_style))
        story.append(Spacer(1, 3))

    story.append(Spacer(1, 10 * mm))
    story.append(HRFlowable(width="100%", color=HexColor("#eeeaf8"), thickness=1))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "Generated by ResumeLens — a BCA college project prototype. "
        "This report is for personal resume improvement only.",
        meta_style,
    ))

    doc.build(story)
    return filepath
